# Generated by Django 5.1.7 on 2025-03-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sduser',
            name='user_type',
            field=models.CharField(default='volunteer', max_length=50),
        ),
    ]
