# Generated by Django 5.1.7 on 2025-03-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sduser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sduser',
            name='user_type',
        ),
    ]
