# Generated by Django 5.1.7 on 2025-03-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Missing_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('health_condition', models.TextField()),
                ('person_contact_number', models.CharField(max_length=20)),
                ('person_to_contact', models.CharField(max_length=20)),
                ('last_known_location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('health_condition', models.TextField()),
                ('personal_number', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('location', models.TextField()),
                ('max_capacity', models.PositiveIntegerField()),
                ('members_in_shelter', models.PositiveIntegerField()),
                ('isFull', models.BooleanField(default=False)),
                ('medical_facilities', models.ManyToManyField(to='data.medical_facility')),
                ('resources', models.ManyToManyField(to='data.resources')),
            ],
        ),
    ]
