# Generated by Django 5.1.7 on 2025-03-23 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_missing_person_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource_avalability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='shelter',
            name='space_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='shelter',
            constraint=models.CheckConstraint(check=models.Q(('max_capacity__gte', models.F('members_in_shelter'))), name='check_members_in_shelter'),
        ),
        migrations.RenameModel(
            old_name='Resources',
            new_name='Resource',
        ),
        migrations.AddField(
            model_name='resource_avalability',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.resource'),
        ),
    ]
