# Generated by Django 5.1.7 on 2025-03-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_resource_avalability_shelter_space_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missing_person',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missing_person',
            name='health_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missing_person',
            name='last_known_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missing_person',
            name='person_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
