# Generated by Django 5.1.7 on 2025-03-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_missing_person_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missing_person',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='victim',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='victim',
            name='personal_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
