# Generated by Django 4.2.20 on 2025-03-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_missing_person_found'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shelter',
            name='check_members_in_shelter',
        ),
    ]
